### ISSUE TITLE
Error: unmatched pseudo-class :focus

### ISSUE THREAD

**Issue by RyanDurkin** [paceaux/selector-finder#2]
I ran the tool this morning against a project that has inherited a bootstrap template and it throws this error in the log:

```
Error: unmatched pseudo-class :focus
    at Object.compilePseudoSelector (C:\Users\Ryan\Documents\Projects\selector-finder\node_modules\css-select\lib\pseudo-selectors\index.js:46:11)
    at Object.compileGeneralSelector (C:\Users\Ryan\Documents\Projects\selector-finder\node_modules\css-select\lib\general.js:21:39)
    at rules.reduce._a (C:\Users\Ryan\Documents\Projects\selector-finder\node_modules\css-select\lib\compile.js:102:25)
    at Array.reduce (<anonymous>)
    at compileRules (C:\Users\Ryan\Documents\Projects\selector-finder\node_modules\css-select\lib\compile.js:99:18)
    at C:\Users\Ryan\Documents\Projects\selector-finder\node_modules\css-select\lib\compile.js:90:16
    at Array.map (<anonymous>)
    at compileToken (C:\Users\Ryan\Documents\Projects\selector-finder\node_modules\css-select\lib\compile.js:76:10)
    at Object.addAdapter [as _compileToken] (C:\Users\Ryan\Documents\Projects\selector-finder\node_modules\css-select\lib\index.js:48:16)
    at findElements (C:\Users\Ryan\Documents\Projects\selector-finder\node_modules\cheerio-select-tmp\lib\index.js:234:30)
```

I then get no results in the pages.json

```
  "totalPagesSearched": 8,
  "totalMatches": 0,
  "pagesWithSelector": []
```

**Comment by paceaux** [comment]
I'll look into this one. This may be hard to identify as `:focus` , `:hover` and `:active` are all "interactive" pseudoclasses. So they may not be findable on a given page.  But I wouldn't want an error in the log for this.

**Comment by RyanDurkin** [comment]
I wouldn't expect it to identify the interactive pseudoclasses either but it would need to extract the selector of the pseudoclass and search for usages of that instead?

**Comment by paceaux** [comment]
oh yes, absolutely. Cheerio itself throws the error, but because I'm not catching it, it bubbles up and cancels the process. So I'll catch the error and add a friendly message.

**Comment by paceaux** [comment]
fun fact: apparently the Cheerio library only throws an error on `:focus`; with `:hover` and `:active` it just doesn't find them. So there's going to be a blend. `:hover` and `:focus` will show up as "unused" and `:focus` will be in a `selectorErrors` property. 

As you may expect, running this in spa mode `-d, --isSpa` doesn't have this issue, because, of course, Puppeteer ain't afraid of a little `:focus`.

**Comment by paceaux** [comment]
Closing this. errors with selectors in Cheerio will be caught. If there's a mix of results and errors, it goes to the json. if there's ONLY selector errors, it goes to the log.
